package com.vamsi.smartroute.sim;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.vamsi.smartroute.model.Tier;
import com.vamsi.smartroute.routing.ComplexityClassifier;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * CALIBRATION — a credit-free look at how well the zero-model-call {@link ComplexityClassifier}
 * picks a STARTING tier, measured against a hand-labeled corpus of prompts (each tagged with the
 * tier a reasonable engineer would want it to start at, and why). No API key, no model calls.
 *
 * <p>The heuristic only sees a proxy for difficulty — length, code fences, and hard-signal
 * keywords — so it will diverge from intent. What matters is the DIRECTION of divergence:
 * <ul>
 *   <li><b>exact</b>   — started at the intended tier;
 *   <li><b>undershoot</b> — started cheaper than intended; SAFE, because {@code SmartRouteService}
 *       escalates on a failed validator, so the only cost is one extra cheap attempt;
 *   <li><b>overshoot</b>  — started more expensive than intended; this is the one to avoid, because
 *       there is no de-escalation — an over-eager start overspends on every such request.
 * </ul>
 * The design deliberately biases toward undershoot. This test asserts that bias holds (no trivial
 * prompt is ever sent to the flagship, and nothing overshoots its intended tier on this corpus)
 * and writes {@code docs/classifier-calibration.md} so the behavior is visible without running it.
 */
class ClassifierCalibrationTest {

    private static final Path CASES_PATH = Path.of("eval/classifier-cases.jsonl");
    private static final Path REPORT_PATH = Path.of("docs/classifier-calibration.md");

    private final ComplexityClassifier classifier = new ComplexityClassifier();
    private final ObjectMapper mapper = new ObjectMapper();

    /** A labeled prompt: what tier a human would want it to START at, and the reasoning. */
    private record Case(String id, String prompt, String expectStart, String intent) {
        Tier expected() { return Tier.valueOf(expectStart); }
    }

    private List<Case> loadCases() throws IOException {
        List<String> lines = Files.readAllLines(CASES_PATH);
        return lines.stream()
                .filter(l -> !l.isBlank())
                .map(l -> {
                    try { return mapper.readValue(l, Case.class); }
                    catch (Exception e) { throw new IllegalStateException("bad case line: " + l, e); }
                })
                .toList();
    }

    @Test
    void classifierBiasesTowardCheapAndNeverOverspendsOnLabeledCorpus() throws IOException {
        List<Case> cases = loadCases();
        assertFalse(cases.isEmpty(), "calibration corpus must not be empty");

        int exact = 0, under = 0, over = 0;
        StringBuilder rows = new StringBuilder();

        for (Case c : cases) {
            Tier start = classifier.classify(c.prompt()).startTier();
            Tier want = c.expected();
            int delta = start.ordinal() - want.ordinal();
            String verdict;
            if (delta == 0)      { exact++; verdict = "exact"; }
            else if (delta < 0)  { under++; verdict = "under ↓"; }
            else                 { over++;  verdict = "OVER ↑"; }

            // Invariant 1: a trivial prompt (intended for Luna) must never start at the flagship.
            if (want == Tier.LUNA) {
                assertNotSame(Tier.SOL, start,
                        "trivial prompt started at SOL — the cheap heuristic overspent: " + c.id() + " / " + c.prompt());
            }
            // Invariant 2: nothing overshoots its intended tier on this curated corpus. Undershoot
            // is fine (escalation recovers it); overshoot has no recovery path and overspends.
            assertTrue(delta <= 0,
                    "overshoot on " + c.id() + ": started " + start + " but intended " + want + " — " + c.prompt());

            rows.append("| ").append(c.id()).append(" | ").append(want).append(" | ").append(start)
                .append(" | ").append(verdict).append(" | ").append(c.intent()).append(" |\n");
        }

        int n = cases.size();
        double exactPct = 100.0 * exact / n;
        String md = """
                # Classifier calibration (credit-free — no model calls)

                How the zero-model-call `ComplexityClassifier` picks a **starting** tier, measured
                against a hand-labeled corpus (`eval/classifier-cases.jsonl`). Generated by
                `ClassifierCalibrationTest` — do not hand-edit.

                The heuristic only sees a proxy for difficulty (length, code fences, hard-signal
                keywords), so it diverges from intent. Direction is what matters:
                **undershoot** is safe (the router escalates on a failed check — one extra cheap
                attempt), **overshoot** is not (there is no de-escalation, so it overspends every
                time). The heuristic is tuned to prefer undershoot.

                Cases: %d  ·  **exact: %d (%.0f%%)**  ·  undershoot: %d  ·  overshoot: %d

                | case | intended start | classifier start | vs. intent | why |
                |------|----------------|------------------|-----------|-----|
                %s
                **Reading this:** overshoot is 0 by design — the classifier never starts above the
                intended tier on this corpus, so it never overspends. The undershoots are the
                heuristic being conservative (e.g. a proof phrased with "deriving" rather than
                "derive", or a lightly-worded trade-off question); escalation catches those at the
                cost of one cheap first attempt. This is the intended trade: a cheap, explainable
                guess that errs toward the cheaper tier and lets validation-driven escalation
                recover the misses. See [simulation-results.md](simulation-results.md) for what that
                costs in aggregate, and [routing-NOTES.md](routing-NOTES.md) for the mechanism.
                """.formatted(n, exact, exactPct, under, over, rows.toString().stripTrailing());

        Files.writeString(REPORT_PATH, md);
    }
}
